SHELL := /bin/bash

PROJECTS ?=
SERVICES := load products customers categories main

# Load the configuration generated by `make init` when it exists.
-include .env
export JAVA_HOME DOCKER_REGISTRY_PUSH DOCKER_REGISTRY_PULL TEST_DOMAIN

.PHONY: help init build push helm-update helm-repos deploy

help:
	@echo "Usage:"
	@echo "  make init                         Configure the local environment"
	@echo "  make build [PROJECTS='...']       Build service JARs"
	@echo "  make push [PROJECTS='...']        Build and push service images"
	@echo "  make deploy                       Deploy the Helm chart"
	@echo ""
	@echo "Without PROJECTS, build and push ask gum to select services."

init:
	@set -euo pipefail; \
		echo "select JAVA_HOME"; \
		java_home="$$(gum file "$${JAVA_HOME:-}/.." --directory)"; \
		echo "Set Docker Registry to push"; \
		registry_push="$$(gum input --placeholder 'Docker Registry to push' --value="$${DOCKER_REGISTRY_PUSH:-localhost:5000}")"; \
		echo "Set Docker Registry to pull"; \
		registry_pull="$$(gum input --placeholder 'Docker Registry to pull' --value="$${DOCKER_REGISTRY_PULL:-$$registry_push}")"; \
		echo "Set Test Domain"; \
		test_domain="$$(gum input --placeholder 'Test Domain' --value="$${TEST_DOMAIN:-example.com}")"; \
		echo "Writing env to [./.env]"; \
		{ \
			echo "JAVA_HOME=$$java_home"; \
			echo "DOCKER_REGISTRY_PUSH=$$registry_push"; \
			echo "DOCKER_REGISTRY_PULL=$$registry_pull"; \
			echo "TEST_DOMAIN=$$test_domain"; \
		} > .env

build:
	@test -f .env || { echo "No .env found; run 'make init' first" >&2; exit 1; }
	@set -euo pipefail; \
		projects="$$(if [[ -n "$(PROJECTS)" ]]; then echo "$(PROJECTS)"; else gum choose --no-limit $(SERVICES); fi)"; \
		for project in $$projects; do \
			echo "Building $$project"; \
			./gradlew :$$project:bootJar; \
		done

push:
	@test -f .env || { echo "No .env found; run 'make init' first" >&2; exit 1; }
	@set -euo pipefail; \
		projects="$$(if [[ -n "$(PROJECTS)" ]]; then echo "$(PROJECTS)"; else gum choose --no-limit $(SERVICES); fi)"; \
		for project in $$projects; do \
			echo "Pushing image $$project"; \
			image="$$DOCKER_REGISTRY_PUSH/services/$$project:latest"; \
			docker buildx build --platform linux/amd64 -t "$$image" ./$$project; \
			docker push "$$image"; \
		done

helm-repos:
	@set -euo pipefail; \
		cd deploy; \
		helm repo add mssqlserver https://raw.githubusercontent.com/zbindenp/mssqlserver/gh-pages

helm-update: helm-repos
	@set -euo pipefail; \
		cd deploy; \
		helm dependency update .

deploy:
	@test -f .env || { echo "No .env found; run 'make init' first" >&2; exit 1; }
	@set -euo pipefail; \
		cd deploy; \
		helm upgrade -i services . -n services --create-namespace \
			--set defaults.ingress.domain="$$TEST_DOMAIN" \
			--set jaeger.jaeger.ingress.hosts[0]="jaeger.$$TEST_DOMAIN" \
			--set defaults.registry="$$DOCKER_REGISTRY_PULL" \
			--history-max 3
