SHELL := /bin/bash

PROJECTS ?=
SERVICES := load products customers main

# Load the configuration generated by `make init` when it exists.
-include .env
export JAVA_HOME \
	DOCKER_REGISTRY_PUSH \
	DOCKER_REGISTRY_PULL \
	TEST_DOMAIN \
	PROM_ENDPOINT \
	PROM_USERNAME \
    PROM_PASSWORD \
    LOGS_ENDPOINT \
    LOGS_USERNAME \
    LOGS_PASSWORD \
    TRACES_ENDPOINT \
    TRACES_USERNAME \
    TRACES_PASSWORD

.PHONY: help init build push helm-update helm-repos deploy deploytest observability observabilitytest

help:
	@echo "Usage:"
	@echo "  make init                         Configure the local environment"
	@echo "  make build [PROJECTS='...']       Build service JARs"
	@echo "  make push [PROJECTS='...']        Build and push service images"
	@echo "  make deploy                       Deploy the Helm chart"
	@echo ""
	@echo "Without PROJECTS, build and push ask gum to select services."

init:
	@set -euo pipefail; \
		echo "select JAVA_HOME"; \
		java_home="$$(gum file "$${JAVA_HOME:-}/.." --directory)"; \
		echo "Set Docker Registry to push"; \
		registry_push="$$(gum input --placeholder 'Docker Registry to push' --value="$${DOCKER_REGISTRY_PUSH:-localhost:5000}")"; \
		echo "Set Docker Registry to pull"; \
		registry_pull="$$(gum input --placeholder 'Docker Registry to pull' --value="$${DOCKER_REGISTRY_PULL:-$$registry_push}")"; \
		echo "Set Test Domain"; \
		test_domain="$$(gum input --placeholder 'Test Domain' --value="$${TEST_DOMAIN:-example.com}")"; \
		echo "Writing env to [./.env]"; \
		{ \
			echo "JAVA_HOME=$$java_home"; \
			echo "DOCKER_REGISTRY_PUSH=$$registry_push"; \
			echo "DOCKER_REGISTRY_PULL=$$registry_pull"; \
			echo "TEST_DOMAIN=$$test_domain"; \
		} > .env

build:
	@test -f .env || { echo "No .env found; run 'make init' first" >&2; exit 1; }
	@set -euo pipefail; \
		projects="$$(if [[ -n "$(PROJECTS)" ]]; then echo "$(PROJECTS)"; else gum choose --no-limit $(SERVICES); fi)"; \
		for project in $$projects; do \
			echo "Building $$project"; \
			./gradlew :$$project:bootJar; \
		done

push:
	@test -f .env || { echo "No .env found; run 'make init' first" >&2; exit 1; }
	@set -euo pipefail; \
		projects="$$(if [[ -n "$(PROJECTS)" ]]; then echo "$(PROJECTS)"; else gum choose --no-limit $(SERVICES); fi)"; \
		for project in $$projects; do \
			echo "Pushing image $$project"; \
			if [[ "$$project" == "load" ]]; then \
			    image="$$DOCKER_REGISTRY_PUSH/services/$$project:latest"; \
 	        	docker buildx build --platform linux/amd64 -t "$$image" ./$$project; \
      			docker push "$$image"; \
			else \
			    ./gradlew :$$project:jib; \
			fi; \
		done

helm-update: helm-repos
	@set -euo pipefail; \
		cd deploy/services; \
		helm dependency update .

deploy:
	@test -f .env || { echo "No .env found; run 'make init' first" >&2; exit 1; }
	@set -euo pipefail; \
		cd deploy/services; \
		helm upgrade -i services . -n services --create-namespace \
			--set defaults.ingress.domain="$$TEST_DOMAIN" \
			--set jaeger.jaeger.ingress.hosts[0]="jaeger.$$TEST_DOMAIN" \
			--set defaults.registry="$$DOCKER_REGISTRY_PULL" \
			--history-max 3

deploytest:
	@test -f .env || { echo "No .env found; run 'make init' first" >&2; exit 1; }
	@set -euo pipefail; \
	    mkdir -p .tmp; \
		helm template deploy/services > .tmp/services.yaml

observability:
	@test -f .env || { echo "No .env found; run 'make init' first" >&2; exit 1; }
	@set -euo pipefail; \
		cd deploy/observability; \
		helm upgrade -i observability . -n observability --create-namespace \
			--set secrets.otel-collector-secrets.PROM_ENDPOINT="$$PROM_ENDPOINT" \
			--set secrets.otel-collector-secrets.PROM_USERNAME="$$PROM_USERNAME" \
			--set secrets.otel-collector-secrets.PROM_PASSWORD="$$PROM_PASSWORD" \
			--set secrets.otel-collector-secrets.LOGS_ENDPOINT="$$LOGS_ENDPOINT" \
			--set secrets.otel-collector-secrets.LOGS_USERNAME="$$LOGS_USERNAME" \
			--set secrets.otel-collector-secrets.LOGS_PASSWORD="$$LOGS_PASSWORD" \
			--set secrets.otel-collector-secrets.TRACES_ENDPOINT="$$TRACES_ENDPOINT" \
			--set secrets.otel-collector-secrets.TRACES_USERNAME="$$TRACES_USERNAME" \
			--set secrets.otel-collector-secrets.TRACES_PASSWORD="$$TRACES_PASSWORD" \
			--history-max 3

observabilitytest:
	@test -f .env || { echo "No .env found; run 'make init' first" >&2; exit 1; }
	@set -euo pipefail; \
	    mkdir -p .tmp; \
		helm template \
			--set secrets.otel-collector-secrets.PROM_ENDPOINT="$$PROM_ENDPOINT" \
			--set secrets.otel-collector-secrets.PROM_USERNAME="$$PROM_USERNAME" \
			--set secrets.otel-collector-secrets.PROM_PASSWORD="$$PROM_PASSWORD" \
			--set secrets.otel-collector-secrets.LOGS_ENDPOINT="$$LOGS_ENDPOINT" \
			--set secrets.otel-collector-secrets.LOGS_USERNAME="$$LOGS_USERNAME" \
			--set secrets.otel-collector-secrets.LOGS_PASSWORD="$$LOGS_PASSWORD" \
			--set secrets.otel-collector-secrets.TRACES_ENDPOINT="$$TRACES_ENDPOINT" \
			--set secrets.otel-collector-secrets.TRACES_USERNAME="$$TRACES_USERNAME" \
			--set secrets.otel-collector-secrets.TRACES_PASSWORD="$$TRACES_PASSWORD" \
			deploy/observability > .tmp/observability.yaml
