apiVersion: apps/v1
kind: Deployment
metadata:
  name: main
  namespace: demo
spec:
  selector:
    matchLabels:
      app: main
  replicas: 1
  template:
    metadata:
      labels:
        app: main
      annotations:
        deployed-at: "$DEPLOY"
    spec:
      containers:
        - name: main
          image: "localhost:5000/services/main:latest"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '0.49'
              memory: "512Mi"
            limits:
              cpu: '0.5'
              ephemeral-storage: "100Mi"
              memory: "512Mi"
          env:
            - name: PRODUCTS_BASE_URL
              value: http://products-service.demo.svc.cluster.local:8080
            - name: CUSTOMERS_BASE_URL
              value: http://customers-service.demo.svc.cluster.local:8080
            - name: OTEL_COLLECTOR
              value: http://otel-collector-service:4318
            - name: DATABASE_HOST
              value: msssql-server.databases.svc.cluster.local
            - name: DATABASE_PORT
              value: "31433"
            - name: DATABASE_USERNAME
              value: sa
            - name: DATABASE_PASSWORD
              value: ${SA_PASSWORD}
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: main-service
  namespace: demo
  labels:
    app: main
spec:
  type: NodePort
  selector:
    app: main
  ports:
    - name: "http"
      port: 8080 # Port wie der Service im kubernetes-cluster erreichbar ist. Default 8080
      targetPort: 8080 # Port welcher im Image verwendet wird. Default
