{{- if .Capabilities.APIVersions.Has "opentelemetry.io/v1alpha1" }}
{{- if hasKey .Values "otel"  }}
{{- $otel := .Values.otel  }}
{{- if and (hasKey $otel "enabled") (eq $otel.enabled true)  }}
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: otel-instrumentation
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
spec:
  exporter:
    endpoint: {{- printf "http://%s.%s.svc.cluster.local:4318" .Values.otel.serviceName .Values.otel.serviceNamespace | quote }}
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
{{- end }}
{{- end }}
{{- end }}