image: "mcr.microsoft.com/mssql/server:2025-latest"
saPassword: "mySuperSecurePassword!"
storage: "1Gi"
# nodePort: 31433
#databases:
# A secret with the name "<dbname>-connection" with connection details will be published
#  aa:
#    user: "aauser"
#    # if not defined, a random password is generated
#    password: "customersPwd@Home"