apiVersion: apps/v1
kind: Deployment
metadata:
  name: catgories
  namespace: demo
spec:
  selector:
    matchLabels:
      app: catgories
  replicas: 1
  template:
    metadata:
      labels:
        app: catgories
      annotations:
        deployed-at: "$DEPLOY"
    spec:
      containers:
        - name: catgories
          image: "localhost:5000/services/catgories:latest"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '0.49'
              memory: "512Mi"
            limits:
              cpu: '0.5'
              ephemeral-storage: "100Mi"
              memory: "512Mi"
          env:
            - name: DATABASE_HOST
              value: msssql.databases.svc.cluster.local
            - name: DATABASE_PORT
              value: "1433"
            - name: DATABASE_USERNAME
              value: sa
            - name: DATABASE_PASSWORD
              value: ${SA_PASSWORD}
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: catgories-service
  namespace: demo
  labels:
    app: catgories
spec:
  type: NodePort
  selector:
    app: catgories
  ports:
    - name: "http"
      port: 8080 # Port wie der Service im kubernetes-cluster erreichbar ist. Default 8080
      targetPort: 8080 # Port welcher im Image verwendet wird. Default
