spring:
  application:
    name: products
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:sqlserver://${DATABASE_HOST:localhost}:${DATABASE_PORT:1433};databaseName=${DATABASE_NAME:products}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:secure}
