{{- range $name, $service := .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace}}
spec:
  selector:
    matchLabels:
      app: {{ $name }}
  replicas: {{ $service.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ $name }}
{{/*      annotations:*/}}
{{/*        deployed-at: "{{ now }}"*/}}
    spec:
      containers:
        - name: {{ $name }}
          image: {{ printf "%s/%s:%s" ($service.image.registry | default $.Values.defaults.registry) $service.image.repository ($service.image.tag | default "latest") }}
          imagePullPolicy: Always
          {{- with ($service.resources | default $.Values.defaults.resources) }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with ($service.startupProbe | default $.Values.defaults.startupProbe)}}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with ($service.livenessProbe | default $.Values.defaults.livenessProbe) }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with ($service.readinessProbe | default $.Values.defaults.readinessProbe) }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $service.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $service.envFrom}}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      automountServiceAccountToken: false
---
{{- end }}