{{- range $dbname, $db := .Values.databases }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-connection" $dbname}}
  namespace: {{$.Release.Namespace}}
type: Opaque
stringData:
  DATABASE_HOST: "{{ printf "mssql-server.%s.svc.cluster.local" $.Release.Namespace}}"
  DATABASE_PORT: "1433"
  DATABASE_USERNAME: "{{ $db.user}}"
  DATABASE_PASSWORD: "{{ $db.password}}"
---
{{- end }}
