{{- range $dbname, $db := .Values.databases }}
{{- $secretName := printf "%s-connection" $dbname }}
{{- $secretObj  := (lookup "v1" "Secret" $.Release.Namespace $secretName) | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
{{- $dbPasswordGenerated := (get $secretData "DATABASE_PASSWORD" | b64dec) | default (randAscii 16) }}
{{- $dbPassword := $db.password | default $dbPasswordGenerated }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-connection" $dbname}}
  namespace: {{$.Release.Namespace}}
type: Opaque
data:
  DATABASE_HOST: "{{ (printf "mssql-server.%s.svc.cluster.local" $.Release.Namespace) | b64enc }}"
  DATABASE_PORT: {{ "1433" | b64enc }}
  DATABASE_USERNAME: "{{ $db.user | b64enc }}"
  DATABASE_PASSWORD: "{{ $dbPassword | b64enc }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "mssql-setup-%s" $dbname}}
  namespace: {{ $.Release.Namespace }}
stringData:
  setup.sql: |
    IF EXISTS (SELECT name FROM master.sys.server_principals WHERE name = '{{ $db.user }}')
    BEGIN
      ALTER LOGIN [{{ $db.user }}] WITH PASSWORD = N'{{ $dbPassword }}';
    END
    ELSE
    BEGIN
      CREATE LOGIN [{{ $db.user }}] WITH PASSWORD = N'{{ $dbPassword }}';
    END
    IF NOT EXISTS(SELECT * FROM sys.databases WHERE name = '{{ $dbname }}')
      CREATE DATABASE [{{ $dbname }}];
      GO
      USE [{{ $dbname }}];
      CREATE USER [{{ $db.user }}] FOR LOGIN [{{ $db.user }}];
      EXECUTE sp_changedbowner '{{ $db.user }}';
      ALTER ROLE db_owner ADD MEMBER [{{ $db.user }}];
    GO
---
{{- end }}
