global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'services'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:1234']
