namespace: "services"

mssql:
  saPassword: "myPassword4Services"
  nodePort: 31444
  databases:
    customers:
      user: "customersUser"
      password: "customerswd@Home"
    products:
      user: "productsUser"
      password: "productsPwd@Home"

defaults:
  registry: "localhost:5000"
  resources:
    requests:
      cpu: "0.2"
      memory: "512Mi"
    limits:
#      cpu: "0.6"
      memory: "512Mi"
  ingress:
    domain: "example.com"

  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8081
      scheme: HTTP
    timeoutSeconds: 1
    periodSeconds: 20
    successThreshold: 1
    failureThreshold: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8081
      scheme: HTTP
    timeoutSeconds: 10
    periodSeconds: 20
    successThreshold: 1
    failureThreshold: 3
  startupProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8081
      scheme: HTTP
    timeoutSeconds: 1
    periodSeconds: 5
    successThreshold: 1
    failureThreshold: 36

#otel:
#  enabled: true
#  serviceName: "observability-daemon-collector"
#  serviceNamespace: "observability"

services:
  customers:
    name: "customers"
    replicaCount: 1
    cpuBoost: true
    labels:
      api: load
    annotations:
      instrumentation.opentelemetry.io/inject-java: true
    image:
      repository: "services/customers"
    envFrom:
      - secretRef:
          name: customers-connection

  products:
    name: "products"
    replicaCount: 1
    cpuBoost: true
    annotations:
      instrumentation.opentelemetry.io/inject-java: true
    image:
      repository: "services/products"
    envFrom:
      - secretRef:
          name: products-connection

  main:
    name: "main"
    replicaCount: 1
    image:
      repository: "services/main"
    annotations:
      instrumentation.opentelemetry.io/inject-java: true
    resources:
      requests:
        cpu: "0.4"
        memory: "512Mi"
      limits:
        cpu: "1.2"
        memory: "512Mi"
    ingress:
      host: main
    env:
      - name: PRODUCTS_BASE_URL
        value: http://products-service.services.svc.cluster.local:8080
      - name: CUSTOMERS_BASE_URL
        value: http://customers-service.services.svc.cluster.local:8080
      - name: LOAD_BASE_URL
        value: http://load-service.services.svc.cluster.local:8080


  load:
    name: "load"
    replicaCount: 3
    image:
      repository: "services/load"
    labels:
      api: load
    annotations:
      instrumentation.opentelemetry.io/inject-go: true
      instrumentation.opentelemetry.io/otel-go-auto-target-exe: '/root/load'
    selector:
      api: load
    resources:
      requests:
        cpu: "0.05"
        memory: "128Mi"
      limits:
        cpu: "0.1"
        memory: "128Mi"
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        scheme: HTTP
      timeoutSeconds: 1
      periodSeconds: 20
      successThreshold: 1
      failureThreshold: 10
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
        scheme: HTTP
      timeoutSeconds: 10
      periodSeconds: 20
      successThreshold: 1
      failureThreshold: 3
    startupProbe:
      httpGet:
        path: /healthz
        port: 8080
        scheme: HTTP
      timeoutSeconds: 1
      periodSeconds: 2
      successThreshold: 1
      failureThreshold: 30
