{{- if .Values.secrets}}
{{- range $name, $val := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name}}
  namespace: {{ $.Release.Namespace }}
type: Opaque
stringData:
{{- range $key, $sec := $val }}
  {{- $key | nindent 2 }}: {{ $sec |quote }}
{{- end }}
{{- end }}
{{- end }}