apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  namespace: demo
spec:
  selector:
    matchLabels:
      app: products
  replicas: 1
  template:
    metadata:
      labels:
        app: products
        app.kubernetes.io/name: products
    spec:
      containers:
        - name: products
          image: "localhost:5000/services/products:latest"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '0.2'
            limits:
              cpu: '0.3'
              ephemeral-storage: "100Mi"
              memory: "1024Mi"
          env:
            - name: OTEL_COLLECTOR
              value: http://otel-collector-service:4318
            - name: DATABASE_HOST
              value: msssql.databases.svc.cluster.local
            - name: DATABASE_PORT
              value: "1433"
            - name: DATABASE_USERNAME
              value: sa
            - name: DATABASE_PASSWORD
              value: ${SA_PASSWORD}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8091
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8091
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8091
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 50
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: products-service
  namespace: demo
  labels:
    app: products
spec:
  type: NodePort
  selector:
    app: products
  ports:
    - name: "http"
      port: 8081 # Port wie der Service im kubernetes-cluster erreichbar ist. Default 8080
      targetPort: 8081 # Port welcher im Image verwendet wird. Default
      nodePort: 30081 # Port über welchen auf den kubernetes-cluster vom Host PC zugegriffen werden kann
---